spring:
  kafka:
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 1
      auto-offset-reset: earliest
kafka:
  brokers:
    url: ark-01.srvs.cloudkafka.com:9094,ark-02.srvs.cloudkafka.com:9094,ark-02.srvs.cloudkafka.com:9094   
  cloudkarafka:
    topic: tbhv6fbd-KAFKA_TOPIC
    username:  tbhv6fbd
    password:  -9Sw3QOgYju91FcbBUkVfWGfmeWV8tcs
    