spring:
  kafka:
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 1
      auto-offset-reset: earliest
kafka:
  brokers:
    url: XXX   
  cloudkarafka:
    topic: XXXX
    username:  XXX
    password:  XXX
    